name: jar 파일 생성 후 ec2 전송 테스트

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Jar
        run: ./gradlew bootJar

      - name: Find Jar File
        run: |
          JAR_FILE=$(find build/libs -name "quiz*.jar" -printf "%f")

      - name: Transfer JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.PEM_KEY }}
          source: "build/libs/${{ env.JAR_FILE }}"
          target: ${{secrets.JAR_TARGET_PATH}}

#      - name: Transfer JARs to Server
#        run: |
#          find build/libs -name "quiz*.jar" -exec scp -i ${{ secrets.PEM_KEY }} {} ${{ secrets.AWS_SERVER_USER }}@${{ secrets.AWS_SERVER_IP }}:/home/ec2-user \;
